// Generated by gencpp from file service_ex/WordCount.msg
// DO NOT EDIT!


#ifndef SERVICE_EX_MESSAGE_WORDCOUNT_H
#define SERVICE_EX_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <service_ex/WordCountRequest.h>
#include <service_ex/WordCountResponse.h>


namespace service_ex
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace service_ex


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::service_ex::WordCount > {
  static const char* value()
  {
    return "2ad41f381ceb337a84acaf3c0801c353";
  }

  static const char* value(const ::service_ex::WordCount&) { return value(); }
};

template<>
struct DataType< ::service_ex::WordCount > {
  static const char* value()
  {
    return "service_ex/WordCount";
  }

  static const char* value(const ::service_ex::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::service_ex::WordCountRequest> should match
// service_traits::MD5Sum< ::service_ex::WordCount >
template<>
struct MD5Sum< ::service_ex::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::service_ex::WordCount >::value();
  }
  static const char* value(const ::service_ex::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_ex::WordCountRequest> should match
// service_traits::DataType< ::service_ex::WordCount >
template<>
struct DataType< ::service_ex::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::service_ex::WordCount >::value();
  }
  static const char* value(const ::service_ex::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::service_ex::WordCountResponse> should match
// service_traits::MD5Sum< ::service_ex::WordCount >
template<>
struct MD5Sum< ::service_ex::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::service_ex::WordCount >::value();
  }
  static const char* value(const ::service_ex::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::service_ex::WordCountResponse> should match
// service_traits::DataType< ::service_ex::WordCount >
template<>
struct DataType< ::service_ex::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::service_ex::WordCount >::value();
  }
  static const char* value(const ::service_ex::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SERVICE_EX_MESSAGE_WORDCOUNT_H
