// Generated by gencpp from file service_ex/WordCountRequest.msg
// DO NOT EDIT!


#ifndef SERVICE_EX_MESSAGE_WORDCOUNTREQUEST_H
#define SERVICE_EX_MESSAGE_WORDCOUNTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace service_ex
{
template <class ContainerAllocator>
struct WordCountRequest_
{
  typedef WordCountRequest_<ContainerAllocator> Type;

  WordCountRequest_()
    : x(0)
    , y(0)  {
    }
  WordCountRequest_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint32_t _x_type;
  _x_type x;

   typedef uint32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::service_ex::WordCountRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::service_ex::WordCountRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WordCountRequest_

typedef ::service_ex::WordCountRequest_<std::allocator<void> > WordCountRequest;

typedef boost::shared_ptr< ::service_ex::WordCountRequest > WordCountRequestPtr;
typedef boost::shared_ptr< ::service_ex::WordCountRequest const> WordCountRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::service_ex::WordCountRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::service_ex::WordCountRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::service_ex::WordCountRequest_<ContainerAllocator1> & lhs, const ::service_ex::WordCountRequest_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::service_ex::WordCountRequest_<ContainerAllocator1> & lhs, const ::service_ex::WordCountRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace service_ex

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::service_ex::WordCountRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::service_ex::WordCountRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_ex::WordCountRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::service_ex::WordCountRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_ex::WordCountRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::service_ex::WordCountRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::service_ex::WordCountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64be90712af6ea79ae6f103da824ffcf";
  }

  static const char* value(const ::service_ex::WordCountRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64be90712af6ea79ULL;
  static const uint64_t static_value2 = 0xae6f103da824ffcfULL;
};

template<class ContainerAllocator>
struct DataType< ::service_ex::WordCountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "service_ex/WordCountRequest";
  }

  static const char* value(const ::service_ex::WordCountRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::service_ex::WordCountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 x\n"
"uint32 y\n"
;
  }

  static const char* value(const ::service_ex::WordCountRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::service_ex::WordCountRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WordCountRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::service_ex::WordCountRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::service_ex::WordCountRequest_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERVICE_EX_MESSAGE_WORDCOUNTREQUEST_H
